Repository alia-peterson/whats-cooking, pull requests merged in 2021-01, with the labels that each got.

#24 Fix beforeEach decleration in recipe/user tests
  test/recipe-test.js
  test/user-test.js
Labels: enhancement

#29 Feature/tag display
  src/css/styles.scss
  src/domUpdates.js
  src/index.html
Labels: bug, enhancement

#37 Feature/search
  src/scripts.js
Labels: bug, enhancement

#40 Make search happen on keyup
  src/scripts.js
Labels: bug

#58 Fix to search by ingredient and name
  src/scripts.js
Labels: bug

#63 Refactor/styling header
  src/css/_base.scss
  src/css/_header.scss
  src/index.html
Labels: bug, enhancement

#75 Refactor/methods
  src/data/ingredient-data.js
  src/data/recipe-data.js
  src/data/users-data.js
  src/domUpdates.js
  src/recipe.js
  src/scripts.js
  src/user.js
  test/recipe-test.js
  test/user-test.js
Labels: bug, enhancement

#76 Refactor/cooked date
  src/scripts.js
  src/user.js
  test/user-test.js
Labels: enhancement

#66 Update README.md
  README.md
Labels: documentation

#82 Refactor/quotes
  dist/index.html
  src/index.html
  src/recipe.js
  src/scripts.js
Labels: enhancement

#84 Add to future iterations
  README.md
Labels: documentation

#85 Finish build
  dist/bundle.js
  dist/index.html
Labels: bug

#86 Update README.md
  README.md
Labels: bug, documentation
